# Generated by Django 5.1.6 on 2025-02-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
