# Generated by Django 5.1.5 on 2025-01-24 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='도서명')),
                ('author', models.CharField(max_length=50, verbose_name='저자')),
                ('publisher', models.CharField(max_length=50, verbose_name='출판사')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='총 보유 수량')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='대출 가능 수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', '대출 중'), ('OVERDUE', '연체'), ('RETURNED', '반납완료')], default='ACTIVE', max_length=10, verbose_name='대출 상태')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name='대출일')),
                ('due_date', models.DateField(verbose_name='반납예정일')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='반납일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='대출 도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대출',
                'verbose_name_plural': '대출 목록',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', '대기중'), ('AVAILABLE', '대출가능'), ('CANCELLED', '취소됨')], default='WAITING', max_length=10, verbose_name='예약 상태')),
                ('reserved_date', models.DateTimeField(auto_now_add=True, verbose_name='예약일')),
                ('expiry_date', models.DateTimeField(verbose_name='예약만료일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='예약 도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약 목록',
                'ordering': ['reserved_date'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
