# Generated by Django 5.1.5 on 2025-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(verbose_name='반납예정일'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='대출일'),
        ),
    ]
