# Generated by Django 5.1.6 on 2025-02-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    # 3가지 타입 : 모델 마이그레이션, 파이썬 함수, SQL 코드
    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=1000)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
